[project]
name = "python-patterns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.115.8",
    "httpx>=0.28.1",
    "pytest>=8.3.4",
    "sqlalchemy>=2.0.38",
]
